# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20170721_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(default=None, max_length=230),
        ),
    ]
