# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20170721_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='tags',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
