# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_categorymodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='tags',
            field=models.CharField(max_length=100),
        ),
    ]
