# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20170722_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='tags',
            field=models.CharField(max_length=200),
        ),
    ]
