# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20170722_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
