# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_postmodel_upvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='ser_images')),
                ('image_url', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
