# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20170723_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=555)),
            ],
        ),
        migrations.RemoveField(
            model_name='objmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='ObjModel',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.PostModel'),
        ),
    ]
